name: Build Forsaken External

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Altere para 6.0.x ou 7.0.x se o projeto for mais antigo

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/FoulzExternal

    - name: Build Project
      run: dotnet build --configuration Release --no-restore
      working-directory: src/FoulzExternal

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Forsaken-External-EXE
        path: src/FoulzExternal/bin/Release/